name: smkn1contoh
version: 1.0.0+5
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  google_fonts: 3.0.1
  flutter_screenutil: 5.6.0
  percent_indicator: 4.2.2
  flutter_svg: 1.1.6
  dotted_border: 2.0.0+3
  shared_preferences: 2.0.15
  cool_alert: 1.1.0
  lottie: 1.4.3
  shimmer: 2.0.0
  syncfusion_flutter_pdfviewer: 20.3.56
  scrollable_positioned_list: 0.3.5
  internet_connection_checker: 1.0.0+1
  intl: 0.17.0
  timeline_tile: 2.0.0
  flutter_local_notifications: 12.0.3
  showcaseview: 2.0.0+1
  camera: 0.10.0+4
  location: 4.4.0
  google_maps_flutter: 2.2.1
  permission_handler: 10.2.0
  flutter_jailbreak_detection: 1.8.0
  app_settings: 4.1.8
  file_picker: 5.2.2
  flutter_widget_from_html: 0.9.0+1
  pull_to_refresh: 2.0.0
  flutter_chat_bubble: 2.0.0
  fluttertoast: 8.1.1
  package_info_plus: 3.0.2
  url_launcher: 6.1.7
  path_provider: 2.0.11
  sqflite: 2.2.2
  youtube_player_flutter: 8.1.1
  screenshot: 1.2.3
  share_plus: 6.3.0
  flutter_downloader: 1.9.1
  firebase_messaging: 14.2.1
  firebase_core: 2.4.1
  cloud_firestore: 4.3.1
  image_picker: 0.8.6
  image_cropper: 3.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/navbar_icons/
    - assets/icons/
    - assets/icons/riport_presensi/
    - assets/icons/menu_home/
    - assets/icons/grid_menu/
    - assets/icons/presensi_icons/
    - assets/icons/setings/
    - assets/lotties/
    - assets/icons/jadwal/
    - assets/json/
  uses-material-design: true

